name = "MEnums"
uuid = "7c338ca5-b20e-417b-9799-aae6c720705e"
authors = ["John Lapeyre <jlapeyre@users.noreply.github.com> and contributors"]
version = "0.6.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
